- composeApp/src/commonMain/kotlin/com/whatever/caramel/core/presentation/BaseViewModel.kt
- composeApp/src/commonMain/kotlin/com/whatever/caramel/core/presentation/UiIntent.kt
- composeApp/src/commonMain/kotlin/com/whatever/caramel/core/presentation/UiSideEffect.kt
- composeApp/src/commonMain/kotlin/com/whatever/caramel/core/presentation/UiState.kt
- composeApp/src/commonMain/kotlin/com/whatever/caramel/feat/sample/presentation/SampleScreen.kt
- composeApp/src/commonMain/kotlin/com/whatever/caramel/feat/sample/presentation/SampleViewModel.kt
- composeApp/src/commonMain/kotlin/com/whatever/caramel/feat/sample/presentation/mvi/SampleIntent.kt
- composeApp/src/commonMain/kotlin/com/whatever/caramel/feat/sample/presentation/mvi/SampleSideEffect.kt
- composeApp/src/commonMain/kotlin/com/whatever/caramel/feat/sample/presentation/mvi/SampleUiState.kt
- closed #28 
- BaseViewModel 구현
- 샘플 화면 및 샘플 뷰모델 구현
- 현재 화면에 해당하는 데이터 초기화 작업을 `ViewModel`의 `init` 블럭내부이 아닌, `Lifecycle`에 따라 초기화 하도록 구현하였습니다. 생명주기를 인식해야하는 경우가 아니라면 `ViewModel`의 `init` 블럭을 사용해서 데이터를 초기화 해도 괜찮을것 같습니다!
- `LocalLifecycleOwner`가 [**Compose1.7.*** 버전이후 Desktop, iOS 등 타플랫폼 생명주기를 인식](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-lifecycle.html)하도록 변경되었다고 해서 내부 코드를 들여다 보긴 했는데,,,, 사실이 맞는지  iOS 환경에서 테스트가 필요합니다! (샘플 화면에서 로직 구현완료..)
- 변경된 `LocalLifecycleOwner`
- Deprecate된 이전 `LocalLifecycleOwner`
- iOS 환경에서 적용된 부분 (`ComposeUIViewController` 내부 구현체에서 확인 가능)
> [Feat] MVI 패턴 적용된 BaseViewModel 구현

- app-ios/iosApp.xcodeproj/project.pbxproj
- app-ios/iosApp/iosApp.entitlements
- feature/login/src/androidMain/kotlin/com/whatever/caramel/feature/login/di/Module.android.kt
- feature/login/src/androidMain/kotlin/com/whatever/caramel/feature/login/social/kakao/KakaoAuthProviderImpl.kt
- feature/login/src/androidMain/kotlin/com/whatever/caramel/feature/login/util/Platform.android.kt
- feature/login/src/commonMain/kotlin/com/whatever/caramel/feature/login/LoginRoute.kt
- feature/login/src/commonMain/kotlin/com/whatever/caramel/feature/login/LoginScreen.kt
- feature/login/src/commonMain/kotlin/com/whatever/caramel/feature/login/LoginViewModel.kt
- feature/login/src/commonMain/kotlin/com/whatever/caramel/feature/login/mvi/LoginIntent.kt
- feature/login/src/commonMain/kotlin/com/whatever/caramel/feature/login/social/apple/AppleAuthenticator.kt
- feature/login/src/commonMain/kotlin/com/whatever/caramel/feature/login/social/apple/AppleUser.kt
- feature/login/src/commonMain/kotlin/com/whatever/caramel/feature/login/util/Platform.kt
- feature/login/src/iosMain/kotlin/com/whatever/caramel/feature/login/di/Module.ios.kt
- feature/login/src/iosMain/kotlin/com/whatever/caramel/feature/login/social/apple/AppleAuthProviderImpl.kt
- feature/login/src/iosMain/kotlin/com/whatever/caramel/feature/login/social/kakao/KakaoAuthProviderImpl.kt
- feature/login/src/iosMain/kotlin/com/whatever/caramel/feature/login/util/Platform.ios.kt
- closed #43 
- iOS Apple 인증 로직 구현
- 애플 인증 기능이 iOS의 Native API에서 제공되는 기능들이라 KMP 환경에서도 그대로 쓸수 있었습니다. 다만, 몇몇 클래스들은 Kotlin으로 변환을 해주어야 하는 작업을 요구합니다. (예시로 NSData 타입인 `identityToken` 은 코틀린에서 사용할 수있는 타입이 아니기에 String으로 변환해주기 위한 작업을 요구합니다.)
- [iOS 애플 로그인 참고 자료](https://haram22.tistory.com/74)
- 로그인 실패시 사용자 취소 에러와 애플 서버측 에러를 콜백으로 `NSError` 객체를 받고 있습니다
- [애플 공식문서](https://developer.apple.com/documentation/authenticationservices/asauthorizationerror-swift.struct/code)에 따르면 인증 에러 코드 중 `canceled`이 사용자 취소 에러 코드이며 나머지는 애플서버 에러 혹은 인증서 관련 에러로 안내하고 있습니다.
- KMP 환경에서 Native Enum Class인 ASAuthorizationErrorCode를 직접 사용할 수 없어 아래와 같이 Kotlin으로 직접 Enum Class로 정의하고 에러 코드에 따른 예외 처리를 할수 있습니다.
```
...
override fun authorizationController(
controller: ASAuthorizationController,
didCompleteWithError: NSError
) {
val …
```
> [Feat] iOS 플랫폼 Apple 로그인 구현

- core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/network/config/CaramelResponseValidator.kt
- core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/network/util/HttpResponseExtension.kt
- #56 
- `getBody()`에서 API 호출 성공, Response의 data가 null인 경우 타입 캐스팅
- `caramelResponseValidator()`에서 BaseResponse 형변환 가능 확인에 따른 분기처리
`val clientException = exception as ResponseException`이 서버에 접근이 성공한 경우에만 Type 캐스팅이 되는 것 같습니다.
`getBody()`의 null 테스트 중에 http로 된 URL이 있었습니다. 현재  `usesCleartextTraffic`설정이 default로 `true`여서 `java.net.UnknownServiceException` 오류가 발생합니다.
`caramelResponseValidator()`에서 해당 부분을 잡을 때 형변환에 실패하면 위의 예외 클래스가 아닌 `ClassCastException`이 발생하여 어떤 예외가 발생했는지 확인이 어렵습니다.
따라서 Type 캐스팅이 가능한 경우와 아닌 경우로 나눠서 구현했습니다.
> [Fix] HttpResponseExtension 로직 오류

- app/src/androidMain/AndroidManifest.xml
- app/src/commonMain/kotlin/com/whatever/caramel/di/initKoin.kt
- core/designsystem/build.gradle.kts
- core/designsystem/src/androidMain/kotlin/com/whatever/caramel/core/designsystem/PickerPreview.kt
- core/designsystem/src/androidMain/kotlin/com/whatever/caramel/core/designsystem/di/Modules.android.kt
- core/designsystem/src/androidMain/kotlin/com/whatever/caramel/core/designsystem/util/HapticController.android.kt
- core/designsystem/src/commonMain/kotlin/com/whatever/caramel/core/designsystem/components/Picker.kt
- core/designsystem/src/commonMain/kotlin/com/whatever/caramel/core/designsystem/di/Modules.kt
- core/designsystem/src/commonMain/kotlin/com/whatever/caramel/core/designsystem/util/HapticController.kt
- core/designsystem/src/iosMain/kotlin/com/whatever/caramel/core/designsystem/di/Modules.ios.kt
- core/designsystem/src/iosMain/kotlin/com/whatever/caramel/core/designsystem/util/HapticController.ios.kt
- #51 
- CaramelTextWheelPicker 구현
- SubComposeLayout 활용
- 아이템이 보여줘야 하는 갯수는 총 3개로 이를 구현하기위해 Picker의 높이를 고정으로 잡았어야 했습니다. 고정된 높이를 잡기 위해 SubComposeLayout을 활용하여 아이템의 높이를 획득하고 `3가지 아이템의 높이 + 아이템 간격 + dividerThickness`를 LazyColumn의 높이로 설정하였습니다. 이때 아이템의 높이를 먼저 획득하고 LazyColumn의 높이를 설정하기 위해 SubComposeLayout을 사용하여 아이템 높이를 획득합니다.
- HapticController
- 컴포즈에서 `LocalHapticFeedback`을 활용하여 햅틱의 강도를 설정할수 있습니다. 하지만 KMP 이슈인지.. 현재 `HapticFeedbackType.TextHandleMove`과 `HapticFeedbackType.LongPress`만 작동하고 있습니다. (다른 타입은 진동이 안울림) 때문에 직접 컨트롤러를 DI로 생성하여 각 플랫폼에서 주입받는 형식으로 구현하였습니다. 향후 햅팁 강도가 여러개로 나눠질 경우 확장성을 대비하여 HapticFeedbackType과 비슷한 형태로 구현될 예정입니다.
- UI 모듈 - DatePicker / TimePicker / MonthPicker 구현
> [Feat] 디자인 시스템 - WheelPicker 컴포넌트 구현

- app/src/commonMain/kotlin/com/whatever/caramel/app/CaramelComposeApp.kt
- core/designsystem/src/commonMain/kotlin/com/whatever/caramel/core/designsystem/animation/SlideInSlideOutSnackbarHost.kt
- core/designsystem/src/commonMain/kotlin/com/whatever/caramel/core/designsystem/components/SnackBar.kt
- core/designsystem/src/commonMain/kotlin/com/whatever/caramel/core/designsystem/foundations/Shapes.kt
- core/designsystem/src/commonMain/kotlin/com/whatever/caramel/core/designsystem/themes/CaramelShape.kt
- feature/couple/invite/src/commonMain/kotlin/com/whatever/caramel/feature/copule/invite/CoupleInviteRoute.kt
- closed #89 
- CaramelSnackbar 구현 a816224d0a22a20b88d1b01caa1a7c5b6d33e6d7
- 디자인 시스템 XXL 사이즈 Radius 추가 6eeb82fa7c4d1e021cdafe4f147523d1675d3de7
- LocalSnackbarHostState
- Feature 모듈 전역에서 사용하기 위해 CompositionLocal를 활용한 방향으로 설계하였습니다.
- SlideInSlideOutSnackbarHost 애니메이션
- Material3의 SnackbarHost 컴포저블을 사용할때 `FadeInFadeOutScale`이라는 고정된 애니메이션이 존재합니다. 요구사항에 맞춰 CaramelSnackbarHost 컴포저블 내부에 `SlideInSlideOutSnackbarHost` 애니메이션을 적용합니다.
> [Feat] 디자인 시스템 - Toast 컴포넌트 구현

- core/designsystem/src/androidMain/kotlin/com/whatever/caramel/core/designsystem/DialogPreview.kt
- core/designsystem/src/commonMain/kotlin/com/whatever/caramel/core/designsystem/components/Dialog.kt
- #104 
- Compound Component 방식으로 Dialog 구현
디자인 시스템에 존재한 다이얼로그를 일전에 공유해주신 [아티클](https://haeti.palms.blog/compose-compound-components)을 보고 구현하였습니다.
컴파운드 컴포넌트 방식으로 설계하였고 현재 버튼의 경우 Scope내의 자식 컴포넌트로 구현되어 있습니다. 이는 버튼 컴포넌트 이슈를 추가하여 추후 변경 시키겠습니다.
> [Feat] Dialog 컴포넌트 구현

- core/ui/src/androidMain/kotlin/com/whatever/caramel/core/ui/list/picker/CaramelTimePickerPreview.kt
- core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/picker/CaramelTimePicker.kt
- closed #102 
- TimePicker UI 구현
- period, hour, minute String 타입 통일
- 디자인 가이드 라인에서 minute가 한 자리일 경우 앞에 '0'을 붙여주기에 Int 형으로 사용할수 없었습니다. 때문에 각각의 타입을 모두 String 형태로 통일 시켜 타입 변환 복잡성을 줄일수 있게 구현하였습니다.
> [Feat] TimePicker 구현

- core/ui/src/androidMain/kotlin/com/whatever/caramel/core/ui/list/picker/CaramelDateMonthPickerPreview.kt
- core/ui/src/androidMain/kotlin/com/whatever/caramel/core/ui/list/picker/CaramelDatePickerPreview.kt
- core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/picker/CaramelDateMonthPicker.kt
- core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/picker/CaramelDatePicker.kt
- core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/picker/model/DateUiSate.kt
- feature/profile/create/src/androidMain/kotlin/com/whatever/caramel/feature/profile/create/ProfileCreateScreenPreviewData.kt
- feature/profile/create/src/commonMain/kotlin/com/whatever/caramel/feature/profile/create/components/step/BirthdayStep.kt
- feature/profile/create/src/commonMain/kotlin/com/whatever/caramel/feature/profile/create/mvi/ProfileCreateState.kt
- closed #101 
- CaramelDateMonthPicker 구현
- DateUiState UI Model 분리
- Picker에 사용되는 Ui Model을 패키지로 분리해서 관리하도록 변경하였습니다.
- DateUiState UI Model 재사용
- DateMonthPicker에서 DateUiState의 day는 사용하지 않지만 UI Model을 재사용해도 충분할것 같아 재사하였습니다. 추후 UI Model 내부에 분리되어야 하는 속성이 있다면, DateMonthUiState / DateUiState 로 분리가 될수 있습니다.
> [Feat] DateMonthPicker 구현

- app/src/commonMain/kotlin/com/whatever/caramel/app/CaramelNavHost.kt
- core/designsystem/src/androidMain/kotlin/com/whatever/caramel/core/designsystem/DialogPreview.kt
- feature/couple/connect/src/androidMain/kotlin/com/whatever/caramel/feature/couple/connect/CoupleConnectScreenPreview.kt
- feature/couple/connect/src/androidMain/kotlin/com/whatever/caramel/feature/couple/connect/CoupleConnectScreenPreviewData.kt
- feature/couple/connect/src/commonMain/kotlin/com/whatever/caramel/feature/couple/connect/CoupleConnectScreen.kt
- feature/couple/connect/src/commonMain/kotlin/com/whatever/caramel/feature/couple/connect/CoupleConnectViewModel.kt
- feature/couple/connect/src/commonMain/kotlin/com/whatever/caramel/feature/couple/connect/components/BottomBar.kt
- feature/couple/connect/src/commonMain/kotlin/com/whatever/caramel/feature/couple/connect/components/Content.kt
- feature/couple/connect/src/commonMain/kotlin/com/whatever/caramel/feature/couple/connect/mvi/CoupleConnectIntent.kt
- feature/couple/connect/src/commonMain/kotlin/com/whatever/caramel/feature/couple/connect/mvi/CoupleConnectState.kt
- feature/couple/connect/src/commonMain/kotlin/com/whatever/caramel/feature/couple/connect/navigation/CoupleConnectNavigation.kt
- feature/couple/invite/src/commonMain/kotlin/com/whatever/caramel/feature/copule/invite/navigation/CoupleNavigation.kt
- feature/profile/create/src/commonMain/kotlin/com/whatever/caramel/feature/profile/create/navigation/ProfileNavigation.kt
- feature/splash/src/commonMain/kotlin/com/whatever/caramel/feature/splash/SplashRoute.kt
- feature/splash/src/commonMain/kotlin/com/whatever/caramel/feature/splash/navigation/SplashNavigation.kt
- closed #110 
- 커플 연결 화면 구현
- 커플 연결 로직 구현
- SubComposeLayout을 활용한 BasicTextField의 PlaceHolder와 cursor 위치 설정
- 디자인 요구사항이 cursor의 위치가 placeHolder의 시작점에 위치해 있어야 했습니다. BasicTextField의 innerTextField 너비를 조절할수 없기 때문에, innerTextField보다 너비가 작은 placeHolder를 Box의 `Alignment.Center`를 사용하여 자리를 잡게 될 경우 양 끝단의 길이가 남게되며 cursor의 위치가 요구사항을 충족하지 못하는 상황을 발생시킵니다. invitationCode의 상태가 empty일 경우 placeHolder 너비 만큼의 Box 레이아웃 길이를 강제로 적용하고, notEmpty일 경우 fillMaxWidth를 적용시켜 요구사항을 충족시킵니다.
> Box의 `Alignment.Center`를 사용했을 때 placeHolder의 길이와 innerTextField의 크기 차이 (파란색 상자가 innerTextField)
```
BasicTextField(
...
) { innerTextField ->
Box(
modifier = Modifier.fillMaxSize(),
contentAlignment = Alignment.Center
) {
Box(contentAlignment = Alignment.Center) {
innerTextField.invoke()
if (code.isEmpty()) {
Text(
text = "코드 연결", …
```
> [Feat] 커플 연결 화면 및 로직 구현

- core/designsystem/src/commonMain/kotlin/com/whatever/caramel/core/designsystem/components/Button.kt
- feature/home/build.gradle.kts
- feature/home/src/androidMain/kotlin/com/whatever/caramel/feature/home/HomeScreenPreview.kt
- feature/home/src/androidMain/kotlin/com/whatever/caramel/feature/home/HomeScreenPreviewData.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeRoute.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeScreen.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeViewModel.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/BottomSheet.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/Header.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/Quiz.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/Todos.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeIntent.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeSideEffect.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeState.kt
- gradle.properties
- gradle/libs.versions.toml
- closed #112 
- closed #114 
- closed #51 
- HomeScreen
- PullToRefresh UI 구현
- 기억할 말 남기기 BottomSheet 구현
- 오늘 일정 리스트 구현
- HomeScreenPreview 구현
- Design-System
- CaramelButton 구현
- Build-Gradle
- `org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.8` 추가
- Immutable-Collections 추가
- '일정 리스트'가 변경될 수 있는 리스트이므로 `ImmutableList`를 사용하여 Recomposition 성능 최적화를 진행합니다.
- 퀴즈 UI 미구현
- FCM 기능이 우선순위로 올라옴에 따라, 퀴즈 UI 구현은 제외하고 구현하였습니다.
> [Feat] 홈 화면 및 CaramelButton 구현

- core/ui/build.gradle.kts
- core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/util/ObserveLifecycleEvent.kt
- feature/setting/src/commonMain/kotlin/com/whatever/caramel/feature/setting/SettingRoute.kt
- feature/setting/src/commonMain/kotlin/com/whatever/caramel/feature/setting/component/UserProfile.kt
- feature/setting/src/commonMain/kotlin/com/whatever/caramel/feature/setting/util/OnLifecycleEvent.kt
- gradle.properties
- #116 
- LifecycleEvent를 감지하는 OnLifecycleEvent 구현
- 설정에서 API 호출 시점을 State가 아닌 Event로 감지하도록 변경
[공식문서](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-lifecycle.html#ios)에 iOS 생명주기 기준으로 어떤 Lifecycle.Event/State가 나오는지 명시되어 있더군요!
말씀해주신대로 예측 뒤로가기가 실행되면 iOS 기준으로 viewDidDisapper가 실행될 것이고 STARTED -> CREATED가 실행되고 있습니다.
구현은 ON_START 부분이 저희가 원하는 초기화 시점이 될 것 같아 ON_START마다 API를 호출하도록 했습니다.
`LifecycleEventObserver`를 통해서 Event를 감지하고 화면이 사라질 때 onDispose로 observer를 해제하게 했습니다. 해당 부분은 많이 사용될 것 같은데 괜찮다면 유틸이나 컴포넌트로 옮기는건 어떤가요?
> [Refactor] 설정 > 커플 정보 API 호출 시점 변경

- app/src/commonMain/kotlin/com/whatever/caramel/app/CaramelNavHost.kt
- core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/mapper/AuthMapper.kt
- core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/mapper/CoupleMapper.kt
- core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/mapper/UserMapper.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/entity/Couple.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/vo/auth/UserAuth.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/vo/couple/CoupleInvitationCode.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/vo/user/UserProfile.kt
- core/testing/src/commonMain/kotlin/com/whatever/caramel/core/testing/constants/TestUserInfo.kt
- core/testing/src/commonMain/kotlin/com/whatever/caramel/core/testing/factory/AuthTestFactory.kt
- core/testing/src/commonMain/kotlin/com/whatever/caramel/core/testing/factory/UserTestFactory.kt
- core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/picker/model/DateUiSate.kt
- core/util/src/commonTest/kotlin/com/whatever/caramel/core/util/DateUtilTest.kt
- feature/profile/edit/src/commonMain/kotlin/com/whatever/caramel/feature/profile/edit/ProfileEditViewModel.kt
- feature/profile/edit/src/commonMain/kotlin/com/whatever/caramel/feature/profile/edit/navigation/ProfileEditNavigation.kt
- feature/setting/src/androidMain/kotlin/com/whatever/caramel/feature/setting/component/data/SettingScreenPreviewData.kt
- feature/setting/src/commonMain/kotlin/com/whatever/caramel/feature/setting/SettingRoute.kt
- feature/setting/src/commonMain/kotlin/com/whatever/caramel/feature/setting/SettingScreen.kt
- feature/setting/src/commonMain/kotlin/com/whatever/caramel/feature/setting/SettingViewModel.kt
- feature/setting/src/commonMain/kotlin/com/whatever/caramel/feature/setting/mvi/SettingSideEffect.kt
- feature/setting/src/commonMain/kotlin/com/whatever/caramel/feature/setting/mvi/SettingState.kt
- feature/setting/src/commonMain/kotlin/com/whatever/caramel/feature/setting/navigation/SettingNavigation.kt
- #120 
- 밀리초로 작성된 날짜들을 문자열로 변경
- User(birthday)
- Couple(expirationDateTime, startDate)
도메인이 바뀌니 전체적으로 다 바뀌네요.. 커밋 단위가 애매해서 전체 파일 변화로 보시는게 편할 것 같습니다.
현재 서버에서는 YYYY-MM-DD로 내려오고 있고 UI는 YYYY.MM.DD를 사용하고 있습니다.
백앤드분들께 여쭤보니 공수가 많이 들지는 않지만 DB에 LocalDate를 저장하고 있다하여 클라이언트에서 Mapper를 통해 변경하도록 했습니다.
기존에 밀리초를 기준으로 LocalDate를 가져오는 로직이었습니다.
하지만 String으로 변경함으로써 파라미터로 String을 받아 파싱하도록 변경되었습니다.
만약 올바른 날짜 형식이 아니라면 현재시간을 기준으로 파싱됩니다.
UI에서 잘못된 날짜가 파싱될 경우 오류를 내보낼건지, 현재날짜라도(초기 설정과 동일) 보여지게 할건지 이야기 해야할 것 같아요!
> [Refactor] 시간 관련 엔티티 자료형 변경 (Long -> String)

- app/src/androidMain/kotlin/com/whatever/caramel/GlobalApplication.kt
- app/src/androidMain/kotlin/com/whatever/caramel/di/Module.android.kt
- app/src/commonMain/kotlin/com/whatever/caramel/app/CaramelComposeApp.kt
- app/src/commonMain/kotlin/com/whatever/caramel/app/CaramelNavHost.kt
- app/src/commonMain/kotlin/com/whatever/caramel/di/Module.kt
- app/src/commonMain/kotlin/com/whatever/caramel/di/initKoin.kt
- app/src/iosMain/kotlin/com/whatever/caramel/MainViewController.kt
- app/src/iosMain/kotlin/com/whatever/caramel/di/Module.ios.kt
- iOS에서 뷰모델 내부 SavedStateHandle으로 인한 런타임 오류 해결
- Android / iOS 플랫폼별 DI 분기처리
> [Fix] CaramelViewModel DI 플랫별로 분기

- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/vo/calendar/ScheduleEditParameter.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/vo/calendar/ScheduleParameter.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/vo/memo/MemoParameter.kt
- core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/calendar/request/CreateScheduleRequest.kt
- core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/calendar/request/UpdateScheduleRequest.kt
- core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/request/CreateMemoRequest.kt
- feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/ContentCreateViewModel.kt
- feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/ContentEditViewModel.kt
- https://www.notion.so/given-dragon/205870f222b980fd8aebe57e3c697b33?source=copy_link
- 컨텐츠 제목/설명 생성 및 수정시에 하나라도 존재하면 허용되도록 수정
> [QA] 컨텐츠 제목/설명 생성 및 수정시에 하나라도 존재하면 허용되도록 수정

- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeScreen.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeViewModel.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/Quiz.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeIntent.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeState.kt
- 홈 화면의 밸런스 게임 결과를 확인 한 후, 다른 화면으로 이동했다가 홈 화면 재진입 시 애니메이션이 동작하던 오류 수정
https://github.com/user-attachments/assets/0be91a92-16c0-46da-818e-350a14c3e186
> [QA] 홈 - 밸런스 게임 카드 애니메이션이 동작 오류 수정

- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/exception/code/ContentErrorCode.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/exception/code/ScheduleErrorCode.kt
- feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/ContentDetailRoute.kt
- feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/ContentDetailViewModel.kt
- feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/mvi/ContentDetailIntent.kt
- feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/mvi/ContentDetailState.kt
- feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/ContentEditRoute.kt
- feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/ContentEditViewModel.kt
- feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/mvi/ContentEditIntent.kt
- feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/mvi/ContentEditSideEffect.kt
- feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/mvi/ContentEditState.kt
- https://www.notion.so/given-dragon/Dialog-207870f222b9809b96c4dca5814fb5e3?source=copy_link
- https://www.notion.so/given-dragon/205870f222b9800f856ad23f358e8982?source=copy_link
- 컨텐츠 조회/삭제
- 컨텐츠 수정화면에서 조회/수정/삭제
에 대해서 Dialog 처리
> [QA] 삭제된 메모 수정/저장 시, 메모 조회시 삭제된 컨텐츠에 대해 Dialog 뜨도록 수정

- feature/profile/edit/src/commonMain/kotlin/com/whatever/caramel/feature/profile/edit/component/EditStartDate.kt
- #136 를 적용하며 설정 > 커플 시작일 수정의 상단 이미지 크기 조정
> [FIX] 커플 시작일 수정 상단 이미지 크기 적용

- app/src/commonMain/kotlin/com/whatever/caramel/app/CaramelNavHost.kt
- app/src/commonMain/kotlin/com/whatever/caramel/app/CaramelViewModel.kt
- app/src/commonMain/kotlin/com/whatever/caramel/mvi/AppIntent.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/usecase/auth/SignInWithSocialPlatformUseCase.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/usecase/couple/GetCoupleRelationshipInfoUseCase.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/usecase/user/CreateUserProfileUseCase.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/usecase/user/RefreshUserSessionUseCase.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/validator/UserValidator.kt
- feature/login/src/commonMain/kotlin/com/whatever/caramel/feature/login/LoginRoute.kt
- feature/login/src/commonMain/kotlin/com/whatever/caramel/feature/login/LoginViewModel.kt
- feature/login/src/commonMain/kotlin/com/whatever/caramel/feature/login/mvi/LoginSideEffect.kt
- feature/login/src/commonMain/kotlin/com/whatever/caramel/feature/login/navigation/LoginNavigation.kt
- feature/profile/create/src/commonMain/kotlin/com/whatever/caramel/feature/profile/create/ProfileCreateRoute.kt
- feature/profile/create/src/commonMain/kotlin/com/whatever/caramel/feature/profile/create/ProfileCreateViewModel.kt
- feature/profile/create/src/commonMain/kotlin/com/whatever/caramel/feature/profile/create/mvi/ProfileCreateSideEffect.kt
- feature/profile/create/src/commonMain/kotlin/com/whatever/caramel/feature/profile/create/navigation/ProfileNavigation.kt
- feature/splash/src/commonMain/kotlin/com/whatever/caramel/feature/splash/SplashRoute.kt
- feature/splash/src/commonMain/kotlin/com/whatever/caramel/feature/splash/SplashViewModel.kt
- feature/splash/src/commonMain/kotlin/com/whatever/caramel/feature/splash/mvi/SplashSideEffect.kt
- feature/splash/src/commonMain/kotlin/com/whatever/caramel/feature/splash/navigation/SplashNavigation.kt
- 스플래쉬, 로그인, 프로필 생성 이후 홈 화면 진입 로직 수정
- coupleId 인메모리 저장 로직은 이슈 등록 후 수정 예정 ce536cad33ff6c42fac5af2ff72d21f833953c20
- 수정해야될 범위 : `CoupleRepository` 에서 coupleId가 필요한 기능들
> [Fix] 최초 커플 연결 이후 CoupleId로 인한 홈 화면 진입 오류 수정

- app/src/commonMain/kotlin/com/whatever/caramel/app/CaramelNavHost.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarRoute.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarScreen.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarViewModel.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/mvi/CalendarIntent.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/mvi/CalendarSideEffect.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/navigation/CalendarNavigation.kt
- feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/ContentCreateViewModel.kt
- feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/navigation/ContentCreateNavigation.kt
- feature/main/src/commonMain/kotlin/com/whatever/caramel/feature/main/MainRoute.kt
- feature/main/src/commonMain/kotlin/com/whatever/caramel/feature/main/navigation/MainNavigation.kt
- 캘린더 바텀시트에서 특정 일자로 일정 생성 버튼 클릭 시 오늘 날짜가 나온 현상 수정
- LocalDateTime을 그대로 주는 경우 NavType을 알지못해 String으로 변환해서 전환
> [QA] 캘린더에서 일정 생성 시 오늘 일정이 나오는 현상 수정

- feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/component/MemoItem.kt
- [매모탭에서 본문 미입력한 메모의 ui 조정필요](https://www.notion.so/given-dragon/ui-212870f222b98057b1dbff516d62f539)
- 메모 생성 조건에 따른 UI 수정
-  제목만 존재 or 내용만 존재 -> 제목 ui로 변경
- 현재 서버에서 내용만 작성한 경우 제목과 내용에 둘다 추가되기에 확인필요
> [QA] 메모 생성 조건에 따라서 UI 조정

- core/designsystem/src/commonMain/kotlin/com/whatever/caramel/core/designsystem/components/Dialog.kt
- [디자인 시스템 - 다이얼로그](https://www.notion.so/given-dragon/205870f222b980a6be18c2e6674e8435)
- 다이얼로그의 제목과 내용이 모두 있는경우에 사이에 Spacer 추가
> [QA] 다이얼로그의 제목만 있는경우 Spacer의 위치 변경

- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarRoute.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarViewModel.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/mvi/CalendarIntent.kt
- [일정이 바로 불러와지지 않음](https://www.notion.so/given-dragon/207870f222b980c891e1ecc069c10743)
- 캘린더 화면 진입 시 설정된 년/월을 기반으로 데이터 불러오도록 변경
> [QA] 일정 작성 이후 캘린더 진입 시 새로고침

- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/entity/Todo.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/component/bottomSheet/TodoList.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/component/calendar/Schedule.kt
- URL은 제목 + 내용에 존재하는 내용 중 첫번째 URL로 설정
- 캘린더 셀의 아이템은 제목 or 본문 중 비어있지 않은 값으로 설정
- 캘린더 바텀시트의 아이템은 제목 or 본문 중 비어있지 않은 값으로 설정
> [FIX] 일정 조건에 따른 UI, URL 수정

- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/entity/Couple.kt
- [커플 기념일 - 시작일을 오늘로 설정하면 발생](https://www.notion.so/given-dragon/205870f222b9802ebc97da0c4ad18f77)
- 커플 엔티티의 `daysTogether`에 +1을 추가
> [QA] 커플 만난일에 대한 계산에 +1 추가

- feature/setting/src/commonMain/kotlin/com/whatever/caramel/feature/setting/SettingScreen.kt
- 화면이 작은 경우 하단의 로그아웃, 탈퇴하기 버튼이 사라지는 것을 막기 위한 스크롤 추가
- 우선 개인정보 처리방침과 로그아웃의 사이의 간격을 고정 DP로 주었는데 안드쪽 확인해보니 이질적인 느낌이 들어서 의견한번 나누고싶습니다.
https://github.com/user-attachments/assets/443d11bd-6324-47e3-9c76-21daa48bfd0a
> [FIX] SettingScreen Scroll추가

- feature/content/detail/src/androidMain/kotlin/com/whatever/caramel/feature/content/detail/ContentDetailPreview.kt
- feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/ContentDetailScreen.kt
- feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/mvi/ContentDetailState.kt
- 컨텐츠 상세의 모드가 스케쥴일 경우, 날짜와 시간 UI를 추가
> [QA] 컨텐츠 상세 - 날짜, 시간 UI 추가

- .pre-commit-config.yaml
- Pre-Commit Hook로 코드 포맷팅 자동화
- 동작 과정
- local에서 커밋 이전에 설정된 Hook이 실행됩니다.
- 커밋 되기전 spotlessApply로 코드를 포맷팅 하여 실패시 커밋 중단과 자동 포맷팅을 성공시 커밋을 진행합니다.
- Pre-Commit Hook 설정 방법
```bash
brew install pre-commit
pip install pre-commit
pre-commit install 
pre-commit run --all-files
``` 
- Pre-Commit 해제 방법
```bash
pre-commit uninstall
```
> [Feat] Pre-Commit Hook 코드 포맷팅 자동화 구현

- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/usecase/auth/SignOutUseCase.kt
- [회원탈퇴 시 토큰 삭제](https://www.notion.so/given-dragon/8083036713414226b266dd26bbdb7106?v=47daa3ead13148f588277f7bbf69bc66&p=21c870f222b98070bf52e32977277273&pm=s)
- `SignOutUseCase`에서 토큰 삭제 추가
- 회원탈퇴 후 앱 종료 -> 앱 재실행을 하면 기존에 남아있는 토큰으로 갱신요청을 보내고 있었습니다.
- 동작 상 큰 문제는 없지만 서버 로그 확인 시 정확한 로그를 확인하기 어려워 토큰을 삭제했습니다.
> [QA] 회원탈퇴 후 토큰을 삭제하도록 변경

- app-ios/iosApp/AppDelegate.swift
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarScreen.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeScreen.kt
- feature/main/src/commonMain/kotlin/com/whatever/caramel/feature/main/MainRoute.kt
- feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/MemoScreen.kt
- [Statusbar 컬러 이슈](https://www.notion.so/given-dragon/8083036713414226b266dd26bbdb7106?v=47daa3ead13148f588277f7bbf69bc66&p=221870f222b980b79813c7ddc1b335d7&pm=s)
- 메인 화면 3개의 탭에서 디자인과 같게 statusbar 컬러 적용
> [QA] 메인 - 홈, 캘린더, 메모 화면 시스템 statusbar 컬러 적용

- core/remote/src/androidMain/kotlin/com/whatever/caramel/core/remote/network/config/TimeZoneHeader.android.kt
- core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/di/Module.kt
- core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/network/config/TimeZoneHeader.kt
- core/remote/src/iosMain/kotlin/com/whatever/caramel/core/remote/network/config/TimeZoneHeader.ios.kt
- [프로필 생성 > 생일에 미래시 적용](https://www.notion.so/given-dragon/QA-Board-205870f222b9804f8356ce9332a73263?p=213870f222b980c7bc66f5cebfe2bf33&pm=s)
- DefaultClient에 타임존 헤더 추가
> [Feat] API 요청시 타임존 헤더 추가

- core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/repository/CoupleRepositoryImpl.kt
- core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/datasource/RemoteCoupleDataSource.kt
- core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/datasource/RemoteCoupleDatsSourceImpl.kt
- [커플 기념일 - 시작일을 오늘로 설정하면 발생](https://www.notion.so/given-dragon/205870f222b9802ebc97da0c4ad18f77?d=335870f222b983b4be0c835701b39aa3)
- RequestBuilder 내부 타임존 헤더 중복 제거
> [Fix] 설정 - 커플 시작일 API 타임존 헤더 중복 제거

- .github/workflows/pr-reminder.yml
- 스케쥴링 시간 오전 8시로 변경
- Free 레포로 인한 깃액션 스케쥴링 지연
- [Schedule](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule) 문서를 참고해주세요.
> [Fix] PR 리마인더 워크플로우 스케쥴링 시간 수정

- feature/home/src/androidMain/kotlin/com/whatever/caramel/feature/home/HomeScreenPreviewData.kt
- feature/home/src/commonMain/composeResources/values/strings.xml
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeScreen.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeViewModel.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/Todos.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/header/DisconnectedCard.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/header/Header.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/quiz/BalanceGameResult.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/quiz/OptionButton.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/quiz/Quiz.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/todo/ContentRoleChip.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/todo/EmptyTodo.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/todo/NudgeCard.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/todo/Todos.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeState.kt
- #288 
- 오늘의 일정 아이템에 '담당자' 컴포넌트 추가
- 패키지 분류
- 컴포넌트가 추가되면서 하나의 파일에서 관리가 힘들어 패키지로 분류했습니다.
> [Feat] 홈 - 오늘의 일정 아이템 담당자 컴포넌트 추가

- core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/mapper/CalendarMapper.kt
- core/designsystem/src/commonMain/kotlin/com/whatever/caramel/core/designsystem/themes/CaramelColor.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/entity/Todo.kt
- feature/calendar/src/androidMain/kotlin/com/whatever/caramel/feature/calendar/component/CalendarScreenPreview.kt
- feature/calendar/src/androidMain/kotlin/com/whatever/caramel/feature/calendar/component/CalendarScreenPreviewData.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/component/calendar/Schedule.kt
- #273 
- 캘린더 셀의 일정 담당자 구현
- 디자인 색상 추가
- 캘린더 프리뷰 구현
- 기존 캘린더에 표시되던 셀 UI를 1개의 컴포저블로 가져가고 일정/휴일/기념일로 나눴습니다.
```
@Composable
private fun ScheduleItem(
modifier: Modifier = Modifier,
content: String,
backgroundColor: Color,
textColor: Color,
onClick: () -> Unit = {}
) {
Text(
modifier =
modifier
.fillMaxWidth()
.background(
color = backgroundColor,
shape = CaramelTheme.shape.xxs,
).padding(horizontal = CaramelTheme.spacing.xxs)
.clickable(
indication = null,
interactionSource = null,
onClick = onClick
),
maxLines = 1,
overflow = TextOverflow.Clip,
text = content,
style = CaramelTheme.typography.label3.bold,
color = textColor,
)
}
```
> [Feat] 캘린더 스케쥴 일정 담당자 UI 구현

- core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/mapper/CalendarMapper.kt
- core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/mapper/ContentMapper.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/entity/Memo.kt
- feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/mvi/ContentDetailState.kt
- feature/memo/src/androidMain/kotlin/com/whatever/caramel/feature/memo/component/MemoScreenPreviewProvider.kt
- closes #304 
- 컨텐츠 조회 API 연동
> [Feat] 컨텐츠 조회 - 일정 담당자 API 연동

- feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/component/MemoItem.kt
- [메모탭에서 컴포넌트 간격 수정 필요](https://www.notion.so/given-dragon/23f870f222b98083816ae41f3d09189e)
- 메모 본문과 메타데이터 사이의 간격 조정
- 메모 본문에서의 줄바꿈 변경
> [QA] 메모 리스트 UI 수정

- core/remote/build.gradle.kts
- feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/ContentDetailScreen.kt
- [상세 페이지 내 일정/태그와 본문 사이 간격이 좁음](https://www.notion.so/given-dragon/23f870f222b9804d9339fa4f9ffe32c2)
- 컨텐츠 조회에서 각 요소들마다 margin을 xl로 변경
> [QA] 상세 페이지 내용 간격 수정

- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/validator/UserValidator.kt
- core/remote/build.gradle.kts
- feature/profile/create/src/commonMain/kotlin/com/whatever/caramel/feature/profile/create/ProfileCreateViewModel.kt
- feature/profile/edit/src/commonMain/kotlin/com/whatever/caramel/feature/profile/edit/ProfileEditViewModel.kt
- [닉네임 생성 규칙 확인](https://www.notion.so/given-dragon/23f870f222b981d68b4bc138b0146a06)
- 닉네임 정규식 변경
- 닉네임 정규식 적용 범위 변경
- 닉네임의 입력은 최대 입력수만 체크하고 다음 Step이나 변경/생성 API를 요청 할 때 정규식과 길이 검사를 진행합니다.
- 프로필 생성 시점에서 currentStep에 따라 nextStep의 로직이 정해지기에 해당 부분 변경사항이 존재합니다.
> [QA] 닉네임 검증 시점 및 정규식 변경

- app-ios/iosApp.xcodeproj/project.pbxproj
- app-ios/iosApp/Info.plist
- core/ui/src/androidMain/kotlin/com/whatever/caramel/core/ui/list/picker/CaramelTimePickerPreview.kt
- core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/picker/CaramelTimePicker.kt
- core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/picker/model/DateUiState.kt
- core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/picker/model/TImeUiState.kt
- feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/ContentCreateScreen.kt
- feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/ContentCreateViewModel.kt
- feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/mvi/ContentCreateIntent.kt
- feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/mvi/ContentCreateState.kt
- feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/ContentEditScreen.kt
- feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/ContentEditViewModel.kt
- feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/mvi/ContentEditIntent.kt
- feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/mvi/ContentEditState.kt
- gradle/libs.versions.toml
- closes #336 
- Android : 1.0.3.1 / 10000309
- iOS : 1.0.4 / 10000401
- 컨텐츠 생성 / 수정 데이트 피커 상태 오류 수정
- 바텀시트 피커의 date, time 상태와 화면에 표시되는 date, time 상태 분리
> [Hotfix] Android-1.0.3.1 / iOS-1.0.4

- core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/repository/ScheduleRepositoryImpl.kt
- toString()을 확장함수가 아닌 override 메소드를 사용하도록 변경
- [스레드](https://whatever-xhr4427.slack.com/archives/C082BGJP546/p1757951101361169)에서의 예시가 잘못되어 있어 해당 PR만 확인해주시면 됩니다.
> [QA] 스케쥴 -> 메모 변환 시 오류 수정

- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarViewModel.kt
- 캘린더 Pull To Refresh하면 Indicator가 사라지지 않는 현상 수정
- `getYearSchedules`를 수정하며 isRefreshing 상태를 변경하는 부분이 누락되어 수정추가했습니다.
> [QA] 캘린더 새로고침 시 Indicator가 유지되는 현상 수정

- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/component/calendar/Schedule.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/model/CalendarUiModel.kt
- [석주님께서 주신 의견](https://www.figma.com/design/CwP0kH9V4EuneQpRUTqofP?node-id=3381-10783#1414706349)이 있어서 우선순위를 변경했습니다 (범위일정 -> 기념일 -> 공휴일 -> 단일일정)
- 이전 구현 내용에 기념일과 공휴일 셀 색상이 잘못 적용되어 있어 해당부분도 같이 수정되었습니다.
> [QA] 캘린더 셀 우선순위 변경
