- .github/ISSUE_TEMPLATE/build.md
- .github/ISSUE_TEMPLATE/discussion.md
- .github/ISSUE_TEMPLATE/docs.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/fix.md
- .github/ISSUE_TEMPLATE/hot-fix.md
- .github/ISSUE_TEMPLATE/refactoring.md
> [Docs] 이슈 템플릿 생성

- .github/workflows/add-pr-to-project.yml
- .github/workflows/auto-assign.yml
- closed #16 
- 리뷰어 및 담당자 자동 지정 안되던 오류 수정
- 레포지토리 토큰추가
- 권한 설정
> [Fix] PR Auto Assign 워크 플로우 오류 수정

- .github/workflows/add-pr-to-project.yml
- .github/workflows/update-end-date-on-merge.yml
- #20 
- PR merge시 null 데이터로 인한 Action 결과 실패 오류 수정
-
> [Fix] update-end-date-on-merge 워크 플로우 오류 수정

- .github/workflows/slack_notifier.yml
- closed #12 
- mobile 레포지토리 슬랙에 연동
- 이슈 관련 알림
- 생성 / 닫기 / 코멘트
- 브랜치 관련 알림
- 생성 / 삭제
- PR 관련 알림
- 생성 / 닫기 / 코멘트 / 리뷰 완료
- 그외 알림
- 커밋된 코드 푸쉬
> [Feat] Git 레포지토리 슬랙 Notification 구현

- app-ios/iosApp/Info.plist
- app/src/androidMain/AndroidManifest.xml
- Android, IOS 세로모드 막았습니다.
- Android의 경우 추후 가로모드 대응이 필요할텐데, 이후 생각해봅시다,, 디자인 등 변경 필요하니
- IOS 테스트 해줄사람~ @ham2174 @RyuSw-cs
> [Feat] And ios 세로모드 고정

- app/src/commonMain/kotlin/com/whatever/caramel/di/initKoin.kt
- core/remote/src/androidMain/kotlin/com/whatever/caramel/core/remote/di/Module.android.kt
- core/remote/src/androidMain/kotlin/com/whatever/caramel/core/remote/network/config/AndroidDeviceIdProvider.kt
- core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/di/Module.kt
- core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/network/config/DeviceIdHeader.kt
- core/remote/src/iosMain/kotlin/com/whatever/caramel/core/remote/di/Module.ios.kt
- core/remote/src/iosMain/kotlin/com/whatever/caramel/core/remote/network/config/IOSDeviceIdProvider.kt
- feature/login/src/commonMain/kotlin/com/whatever/caramel/feature/login/LoginScreen.kt
- Android와 iOS 각 플랫폼에 맞는 DeviceIdProvider 구현을 추가하고, Koin 사용하여 의존성 주입함(처음 써보니 리뷰 부탁)
- 작업하고 싶으면 빠른 리뷰 바람..(협박아님)
> [Feat] Device Id 헤더에 추가

- core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/datasource/RemoteTagDataSourceImpl.kt
> [Fix] /tags -> v1/tags 엔드포인트 변경

- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarScreen.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarViewModel.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/component/bottomSheet/Header.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/component/calendar/Schedule.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/mvi/CalendarState.kt
- #133 
- 기념일 API을 통해서 받은 값을 UI에 연동
- 현재 기념일 이미지의 해상도가 1개밖에 없어 크게 나오고 있습니다.
- #136 에서 해상도 폴더가 만들어진 이후 수정하겠습니다.
- 기능 우선 구현을 위해서 해당 기능은 QA 기간에 진행 될 예정입니다.
> [Refactor] 캘린더 기념일 UI 구현 및 API 응답값 연동

- app-ios/iosApp.xcodeproj/project.pbxproj
> [Build] Configuration 프로젝트 파일 수정

- feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/ContentDetailScreen.kt
- feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/ContentDetailViewModel.kt
- feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/mvi/ContentDetailIntent.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeViewModel.kt
- https://www.notion.so/given-dragon/205870f222b98072926bf9e552daaa41?source=copy_link
- 상세화면 뒤로가기 추가
> [QA] 상세화면 뒤로가기

- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeRoute.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeViewModel.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeIntent.kt
- feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/MemoRoute.kt
- feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/MemoViewModel.kt
- feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/mvi/MemoIntent.kt
- 홈, 메모 진입 마다 데이터를 불러오도록 수정
- 캘린더는 날짜만 변경안되도록 수정 예정
> [QA] 홈, 메모 진입 마다 데이터를 불러오도록 수정

- feature/main/src/commonMain/kotlin/com/whatever/caramel/feature/main/MainRoute.kt
- 메인 탭 이동간 애니메이션 제거
https://github.com/user-attachments/assets/ccddafb1-1cc4-4d45-8ac3-3afa3b031c36
> [QA] 메인 - 탭 화면 이동 애니메이션 제거

- app/src/androidMain/kotlin/com/whatever/caramel/Previews.kt
> [FIX] 사용안하는 typo 프리뷰 제거

- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarRoute.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarScreen.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/component/bottomSheet/TodoList.kt
- 링크가 존재하는 스케쥴 아이템에 대한 UI 수정
- 링크 클릭 시 웹 브라우저 이동
https://github.com/user-attachments/assets/9f188404-97fd-4d86-8b48-6deeb83e0d85
> [QA] 캘린더 BottomSheet의 스케쥴 UI 수정

- feature/profile/edit/src/commonMain/kotlin/com/whatever/caramel/feature/profile/edit/ProfileEditRoute.kt
- feature/profile/edit/src/commonMain/kotlin/com/whatever/caramel/feature/profile/edit/ProfileEditViewModel.kt
- feature/profile/edit/src/commonMain/kotlin/com/whatever/caramel/feature/profile/edit/mvi/ProfileEditSideEffect.kt
- feature/setting/src/commonMain/kotlin/com/whatever/caramel/feature/setting/component/BottomSheet.kt
- 설정에 적용된 프로필 편집의 DatePicker에 대한 햅틱 적용
- 프로필 편집 BottomSheet의 배경색 설정
> [QA] 설정 - 프로필 편집

- app/src/androidMain/kotlin/com/whatever/caramel/MainActivity.kt
- https://www.notion.so/given-dragon/StatusBar-205870f222b98016950be1bc743790a9?source=copy_link
- statusbar Light, Navigation 투명하게 적용
> [QA] Status bar 및 Navigation bar 적용

- feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/ContentCreateViewModel.kt
- https://www.notion.so/given-dragon/205870f222b98092bc79ecc5f63c5cd4?source=copy_link
- 메모 - 일정 변경 시 현재시간 반올림하여 5분으로 맞추도록 함
> [QA] 메모 - 일정 변경 시 시간 오류

- core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/repository/CalendarRepositoryImpl.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/vo/calendar/ScheduleEditParameter.kt
- core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/calendar/request/UpdateScheduleRequest.kt
- feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/ContentEditViewModel.kt
- https://www.notion.so/given-dragon/205870f222b980738b9dd2bd1821b9a5?source=copy_link
- [QA] 메모수정 - 메모 → 캘린더 전환
> [QA] 메모수정 - 메모 → 캘린더 전환

- app-ios/iosApp.xcodeproj/project.pbxproj
- app-ios/iosApp/Info.plist
- app/src/iosMain/kotlin/com/whatever/caramel/di/Module.ios.kt
- gradle/libs.versions.toml
> [Chore] 빌드 번호 올림 및 에러 수정

- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/component/bottomSheet/BottomSheetHandle.kt
- feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/component/bottomSheet/Header.kt
- [캘린더 > 리스트뷰에서 간격 조정 필요](https://www.notion.so/given-dragon/207870f222b98068a1d9e13563bc3167)
- [캘린더 모드에서 모달 헤더가 좀 더 내려가야함](https://www.notion.so/given-dragon/211870f222b98016b1a3ed22ab719a33)
- [캘린더 플래그 UI 조정 필요](https://www.notion.so/given-dragon/UI-20a870f222b9803f8ff9c67025c4a9c7)
- 상기 이슈 작업 진행
> [QA] 캘린더 UI 수정

- app/src/commonMain/kotlin/com/whatever/caramel/app/CaramelComposeApp.kt
- feature/splash/src/commonMain/kotlin/com/whatever/caramel/feature/splash/SplashScreen.kt
- [화면 백스택 설정](https://www.notion.so/given-dragon/213870f222b980968272e327461b5bbf)
- ComposeApp에서 처리되는 navigate시, 전체 스택을 없애는 것으로 변경
> [Feat] ComposeApp에서 처리되는 navigate시, 전체 스택을 없애는 것으로 변경

- feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/ContentCreateViewModel.kt
- feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/navigation/ContentCreateNavigation.kt
-  [Fix] Content Create Navigation Argument에서 enum 제거
> [Fix] Content Create Navigation Argument에서 enum 제거

- app/build.gradle.kts
- gradle/libs.versions.toml
- [Chore] Android Build Version Upgrade
- 1.0.0
- 10000000
> [Chore] Android Build Version Upgrade

- gradle/libs.versions.toml
- Android - Version Name Upgrade
- 10000000 -> 10000001
> [Chore] Android - Version Name Upgrade (10000001)

- gradle/libs.versions.toml
- Android - Version Name Upgrade
- 10000001 -> 10000002
> [Chore] Android - version name upgrade (10000001 -> 10000002)

- README.md
- Read.me 작성
- Overview
- Architecture
- Libraries
- Contact & Contributor
- 이 외에 추가 사항 있으면 코멘트 남겨주세요!
> [Docs] Read.me 초기화

- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeViewModel.kt
> [QA] 홈 - 오늘 일정 리스트 삭제시 아이템이 남아있던 오류 수정

- .github/workflows/issue-closed.yml
- closed #239 
-  이슈 종료 알림 메세지 출력 오류 수정
> [Fix] Slack Notifier - 이슈 종료 알림 메세지 출력 오류 수정

- core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/util/InputTextValidation.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeState.kt
- iOS 에서 홈-공유메세지 바텀시트 열었을 때 앱이 크래시나던 오류 수정
> [Fix] iOS - 정규식 문제 수정

- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeViewModel.kt
> [FIX] 오늘의 일정에 제목이 없는 경우 내용으로 수정

- .github/workflows/add-pr-to-project.yml
- FIELD_ID -> STATUS_FIELD_ID 로 변경
- 시크릿값 수정으로 깃 프로젝트 변경되어 적용 됩니다.
- 노션에 키값 획득 방법 및 키값을 문서화 해놓았습니다. [링크](https://www.notion.so/given-dragon/Document-196870f222b9800bb42bed00bca6a1f4?p=222870f222b980b9af85c7775218ad63&pm=s)
> [Refactor] 깃액션 시크릿 키 변경으로 인한 키값 수정

- .github/workflows/pr-reminder.yml
- 오전 10시 마다 발생하는 PR 리마인더 슬랙 알림구현
> [Feat] PR 리마인더 워크플로우 구현

- .github/workflows/pr-reminder.yml
> [Fix] PR 리마인더 eof 구문 오류 수정

- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/vo/content/ContentRole.kt
- #268 
- ContentRole enum class 추가
> [FEAT] 컨텐츠(일정, 메모)의 소유자 enum class 생성

- .github/workflows/pr-reminder.yml
> [Fix] PR 리마인더 슬랙 메세지 형식 오류 수정

- .github/workflows/pr-reminder.yml
> [Fix] PR 리마인더 gh 로그인 오류 수정

- app-ios/iosApp.xcodeproj/project.pbxproj
- app-ios/iosApp/Info.plist
- feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/ContentCreateViewModel.kt
- gradle/libs.versions.toml
- closes #341 
- Android : 1.0.3.2 / 10000310
- iOS : 1.0.5 / 1000501
- 컨텐츠 생성 상태 초기화 누락 코드 추가
> [Hotfix] Android-1.0.3.2/iOS-1.0.5

- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/validator/ContentValidator.kt
- core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/validator/UserValidator.kt
- core/util/src/commonMain/kotlin/com/whatever/caramel/core/util/CodePointCount.kt
- feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/ContentCreateViewModel.kt
- feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/ContentEditViewModel.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeViewModel.kt
- feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeState.kt
- #350 
- User Policy 적용
- Content Policy 적용
- CodePointCount 함수 모듈 변경
> [Refactor] 도메인 - Validator
